LATEST_VERSION = 5.0  # 最新版本号
SERVICE_COUNT = 1e4  # 服务数量
EDGE_SERVER_COUNT = 1  # 边缘服务器数量
USER_COUNT = 5  # 用户数量
FEATURE_VECTOR_SIZE = 256  # 特征向量维度
CANVAS_SIZE_X = 300  # 画布大小X轴(KM)
CANVAS_SIZE_Y = 100  # 画布大小Y轴(KM)
ENABLE_SLEEP = False  # 是否允许用户睡眠

NEW_SERVICE_UPLOAD_PROBABILITY = 1e-3  # 一定概率有新服务上传
SERVICE_CHARM_CAUSAL_CHANGE_PROBABILITY = 1e-3
SERVICE_CHARM_ABRUPT_CHANGE_PROBABILITY = 1e-5
ENABLE_CHARM_CHANGE = False  # 是否允许服务魅力值变化
USER_CHANGE_FAVOR_PROBABILITY = 1e-5
MAKE_TREND_PROBABILITY = 1e-4

DEBUG = True  # 是否开启调试模式(提高带宽)
ENABLE_VISUALIZATION = False  # 是否启动可视化
PRINT_DOWNLOAD_PERCENTAGE = True  # 打印下载进度
PRINT_ES_STATUS = False  # 打印ES状态
